# Wprowadzenie do sztucznej inteligencji i uczenia maszynowego

### Ćwiczenia 2. — Zadania.

#### Zaimportuj biblioteki numpy i pandas.

In [2]:
import numpy as np
import pandas as pd

#### Załaduj plik csv.
***
Do zmiennej `df` załaduj plik `cars.csv`.

In [3]:
df = pd.read_csv("cars.csv")

W ten sposób otrzymujemy obiekt typu Dataframe.

#### Wyświetl pierwsze 5 linijek obiektu ''df''.

In [4]:
df.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7

#### Wyświetl ostatnie 20 linijek obiektu ''df''.

In [5]:
df.tail(20)

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
38511,Chrysler,PT Cruiser,automatic,orange,237000,2004,gasoline,False,gasoline,2.4,...,True,True,True,True,True,True,True,True,True,159
38512,Chrysler,Grand Voyager,automatic,other,280000,2002,gasoline,False,gasoline,3.3,...,True,False,False,False,False,False,False,True,False,160
38513,Chrysler,Sebring,automatic,red,200000,2003,gasoline,False,gasoline,2.4,...,True,False,False,True,True,False,False,True,True,160
38514,Chrysler,Voyager,automatic,red,300000,2002,gas,True,gasoline,2.4,...,True,False,False,False,False,False,False,False,False,161
38515,Chrysler,Grand Voyager,automatic,green,210000,1999,gas,True,gasoline,3.3,...,True,False,False,False,False,False,False,False,True,163
38516,Chrysler,Grand Voyager,automatic,grey,179000,1998,gasoline,False,gasoline,3.3,...,True,False,False,False,False,False,False,False,True,167
38517,Chrysler,Voyager,mechanical,silver,240000,2005,diesel,False,diesel,2.5,...,True,False,False,False,True,False,True,True,True,177
38518,Chrysler,PT Cruiser,automatic,blue,177000,2003,gasoline,False,gasoline,2.4,...,True,False,False,False,False,False,False,False,False,181
38519,Chrysler,Voyager,automatic,brown,200000,1997,gasoline,False,gasoline,2.4,...,True,False,False,False,False,False,False,False,False,186
38520,Chrysler,Voyager,mechanical,silver,400000,1999,diesel,False,diesel,2.5,...,True,False,False,False,False,False,False,False,False,202
38521,Chrysler,Neon,mechanical,green,260000,1995,gasoline,False,gasoline,2.0,...,True,False,False,False,False,False,False,False,True,215
38522,Chrysler,PT Cruiser,automatic,other,207605,2004,gasoline,False,gasoline,2.4,...,True,False,False,False,False,False,False,False,False,221
38523,Chrysler,Grand Voyager,mechanical,black,278000,1999,diesel,False,diesel,2.5,...,True,True,False,True,False,False,False,False,True,239
38524,Chrysler,300,automatic,silver,240000,2001,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,264
38525,Chrysler,Voyager,mechanical,violet,317000,1999,gas,True,gasoline,2.0,...,False,False,True,False,False,False,False,False,True,269
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,301
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,False,False,True,True,False,False,True,True,317
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,369
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,True,False,False,False,False,False,False,False,True,490
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,False,False,False,False,False,False,True,632

#### Wyświetl podstawowe informacje o naszych danych.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38531 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38531 non-null  object
 1   model_name         38531 non-null  object
 2   transmission       38531 non-null  object
 3   color              38531 non-null  object
 4   odometer_value     38531 non-null  int64
 5   year_produced      38531 non-null  int64
 6   engine_fuel        38531 non-null  object
 7   engine_has_gas     38531 non-null  bool
 8   engine_type        38531 non-null  object
 9   engine_capacity    38521 non-null  float64
 10  body_type          38531 non-null  object
 11  has_warranty       38531 non-null  bool
 12  state              38531 non-null  object
 13  drivetrain         38531 non-null  object
 14  price_usd          38531 non-null  float64
 15  is_exchangeable    38531 non-null  bool
 16  location_region    38531 non-null  object
 17  number_of_photos   38531 non-null  int64
 18  up_counter         38531 non-null  int64
 19  feature_0          38531 non-null  bool
 20  feature_1          38531 non-null  bool
 21  feature_2          38531 non-null  bool
 22  feature_3          38531 non-null  bool
 23  feature_4          38531 non-null  bool
 24  feature_5          38531 non-null  bool
 25  feature_6          38531 non-null  bool
 26  feature_7          38531 non-null  bool
 27  feature_8          38531 non-null  bool
 28  feature_9          38531 non-null  bool
 29  duration_listed    38531 non-null  int64
dtypes: bool(13), float64(2), int64(5), object(10)
memory usage: 5.5+ MB

#### Wyświetl wymiary obiektu "df".

In [7]:
df.shape

(38531, 30)

#### Jak otrzymać informacje o danych liczbowych znajdujących się w naszym pliku?

In [8]:
df.describe

<bound method NDFrame.describe of       manufacturer_name  model_name transmission   color  odometer_value  \
0                Subaru     Outback    automatic  silver          190000
1                Subaru     Outback    automatic    blue          290000
2                Subaru    Forester    automatic     red          402000
3                Subaru     Impreza   mechanical    blue           10000
4                Subaru      Legacy    automatic   black          280000
...                 ...         ...          ...     ...             ...
38526          Chrysler         300    automatic  silver          290000
38527          Chrysler  PT Cruiser   mechanical    blue          321000
38528          Chrysler         300    automatic    blue          777957
38529          Chrysler  PT Cruiser   mechanical   black           20000
38530          Chrysler     Voyager    automatic  silver          297729

       year_produced engine_fuel  engine_has_gas engine_type  engine_capacity  \
0               2010    gasoline           False    gasoline              2.5
1               2002    gasoline           False    gasoline              3.0
2               2001    gasoline           False    gasoline              2.5
3               1999    gasoline           False    gasoline              3.0
4               2001    gasoline           False    gasoline              2.5
...              ...         ...             ...         ...              ...
38526           2000    gasoline           False    gasoline              3.5
38527           2004      diesel           False      diesel              2.2
38528           2000    gasoline           False    gasoline              3.5
38529           2001    gasoline           False    gasoline              2.0
38530           2000    gasoline           False    gasoline              2.4

       ... feature_1  feature_2 feature_3 feature_4  feature_5  feature_6  \
0      ...      True       True      True     False       True      False
1      ...      True      False     False      True       True      False
2      ...      True      False     False     False      False      False
3      ...     False      False     False     False      False      False
4      ...      True      False      True      True      False      False
...    ...       ...        ...       ...       ...        ...        ...
38526  ...      True      False     False      True       True      False
38527  ...      True      False     False      True       True      False
38528  ...      True      False     False      True       True      False
38529  ...      True      False     False     False      False      False
38530  ...     False      False     False     False      False      False

      feature_7  feature_8  feature_9  duration_listed
0          True       True       True               16
1         False      False       True               83
2         False       True       True              151
3         False      False      False               86
4         False      False       True                7
...         ...        ...        ...              ...
38526     False       True       True              301
38527     False       True       True              317
38528     False       True       True              369
38529     False      False       True              490
38530     False      False       True              632

[38531 rows x 30 columns]>

#### Jak otrzymać informacje o wszystkich danych znajdujących się w naszym pliku?
***
Funkcja potrzebuje parametru `include = "all"`.

In [9]:
df.describe(include = "all")

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
count,38531,38531,38531,38531,38531.000000,38531.000000,38531,38531,38531,38521.000000,...,38531,38531,38531,38531,38531,38531,38531,38531,38531,38531.000000
unique,55,1118,2,12,NaN,NaN,6,2,3,NaN,...,2,2,2,2,2,2,2,2,2,NaN
top,Volkswagen,Passat,mechanical,black,NaN,NaN,gasoline,False,gasoline,NaN,...,True,False,False,False,False,False,False,False,True,NaN
freq,4243,1423,25633,7705,NaN,NaN,24065,37184,25647,NaN,...,23396,29907,27904,29227,24811,31943,28369,22528,22325,NaN
mean,NaN,NaN,NaN,NaN,248864.638447,2002.943734,NaN,NaN,NaN,2.055161,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.577249
std,NaN,NaN,NaN,NaN,136072.376530,8.065731,NaN,NaN,NaN,0.671178,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.826569
min,NaN,NaN,NaN,NaN,0.000000,1942.000000,NaN,NaN,NaN,0.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,158000.000000,1998.000000,NaN,NaN,NaN,1.600000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.000000
50%,NaN,NaN,NaN,NaN,250000.000000,2003.000000,NaN,NaN,NaN,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.000000
75%,NaN,NaN,NaN,NaN,325000.000000,2009.000000,NaN,NaN,NaN,2.300000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.000000
max,NaN,NaN,NaN,NaN,1000000.000000,2019.000000,NaN,NaN,NaN,8.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2232.000000

#### Wyświetl wszystkie kolumny znajdujące się w naszym obiekcie.

In [10]:
df.columns

Index(['manufacturer_name', 'model_name', 'transmission', 'color',
       'odometer_value', 'year_produced', 'engine_fuel', 'engine_has_gas',
       'engine_type', 'engine_capacity', 'body_type', 'has_warranty', 'state',
       'drivetrain', 'price_usd', 'is_exchangeable', 'location_region',
       'number_of_photos', 'up_counter', 'feature_0', 'feature_1', 'feature_2',
       'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7',
       'feature_8', 'feature_9', 'duration_listed'],
      dtype='object')

#### Wyświetl typy danych, jakie występują w poszczególnych kolumnach obiektu "df".

In [11]:
df.dtypes

manufacturer_name     object
model_name            object
transmission          object
color                 object
odometer_value         int64
year_produced          int64
engine_fuel           object
engine_has_gas          bool
engine_type           object
engine_capacity      float64
body_type             object
has_warranty            bool
state                 object
drivetrain            object
price_usd            float64
is_exchangeable         bool
location_region       object
number_of_photos       int64
up_counter             int64
feature_0               bool
feature_1               bool
feature_2               bool
feature_3               bool
feature_4               bool
feature_5               bool
feature_6               bool
feature_7               bool
feature_8               bool
feature_9               bool
duration_listed        int64
dtype: object

#### Wyświetl dane z konkretnej kolumny.
***

Wyświetl dane z kolumny `'model_name'` na dwa sposoby.

In [12]:
df["model_name"]

0           Outback
1           Outback
2          Forester
3           Impreza
4            Legacy
            ...
38526           300
38527    PT Cruiser
38528           300
38529    PT Cruiser
38530       Voyager
Name: model_name, Length: 38531, dtype: object

#### Stwórz podzbiór, który zawiera tylko wymienione kolumny.
***
Obiekt o nazwie `df_2_columns` powinien zawierać tylko kolumny `'manufacturer_name'` i `'model_name'`

In [13]:
df_2_columns = df[["manufacturer_name","model_name"]]

#### Skopiuj podzbiór do nowego obiektu.
***
Stwórz tzw. "hard copy" obiektu `df` do obiektu `df_copy`.

In [14]:
df_copy = df_2_columns.copy()

#### Stwórz podzbiór zawierający losowe dane i skopiuj do nowego obiektu.
***
Nowy obiekt `df_subset` powinien zawierać 3000 losowo wybranych wierszy z obiektu "df" i powinien być tzw. "hard copy".

In [15]:
df_subset= df.sample(n=3000).copy()

#### Zmień typ danych.
***
W obiekcie `df_subset`, sprawdź typ danych w kolumnie `'transmission'`, a następnie zmień go na typ `'category'`.

In [16]:
df_subset["transmission"]=df_subset["transmission"].astype("category")
df_subset["transmission"].dtype

CategoricalDtype(categories=['automatic', 'mechanical'], ordered=False, categories_dtype=object)

#### Wyeksportuj obiekt do pliku .csv.
***
Zapisz dwa razy obiekt `df_subset` w formacie csv. Raz bez dodatkowych parametrów, oprócz nazwy, a drugi raz z parametrem `index = False`. Użyj dwóch różnych nazw!

In [17]:
df.to_csv("random_index.csv")

In [18]:
df.to_csv("random_noindex.csv", index = False)

#### Wczytaj zapisane obiekty.
***
Wczytaj do dwóch różnych obiektów (nazwy obiektów inne niż "df") i wyświetl wyeksportowane obiekty. Czy jest między nimi jakaś różnica?

In [19]:
df1 = pd.read_csv("random_index.csv")

In [20]:
df2 = pd.read_csv("random_noindex.csv")

#### Sprawdź, który typ danych jest najszybciej czytany i zapisywany
***
Poniżej znajduje się kod do tworzenia losowych danych i nadawania im odpowiednich typów.
```python
def get_dataset(size):
    df = pd.DataFrame()
    df['size'] = np.random.choice(['big','medium','small'], size)
    df['age'] = np.random.randint(1, 50, size)
    df['color'] = np.random.choice(['red','blue','yellow','green'], size)
    df['win'] = np.random.choice(['yes','no'], size)
    dates = pd.date_range('2020-01-01', '2022-12-31')
    df['date'] = np.random.choice(dates, size)
    df['probability'] = np.random.uniform(0, 1, size)
    return df

def set_dtypes(df):
    df['size'] = df['size'].astype('category')
    df['color'] = df['color'].astype('category')
    df['age'] = df['age'].astype('int16')
    df['win'] = df['win'].map({'yes':True, 'no': False})
    df['probability'] = df['probability'].astype('float32')
    return df
```
Użyj tych funkcji do stworzenia i nadania typu danym (size = 5 000 000). <br>
Następnie przy pomocy funkcji `%time` zmierz czas potrzebny do zapisania i wczytania tych danych w różnych formatach m.in.:
- csv
- pickle
- parquet
- feather

Przykład kodu:

```python
print('Reading and writing CSV')
df = get_dataset(5_000_000)
df = set_dtypes(df)
%time df.to_csv('test.csv')
%time df_csv = pd.read_csv('test.csv')
```
***

Jeśli korzystasz ze swojego komputera, upewnij się, że masz zainstalowaną bibliotekę PyArrow, aby móc wczytywać i zapisywać pliki w formacie Parquet i Feather. Korzystając z platformy Colab, nie musisz się tym martwić, ponieważ biblioteka jest już zainstalowana.

In [21]:



def get_dataset(size):

    df = pd.DataFrame()
    df['size'] = np.random.choice(['big','medium','small'], size)
    df['age'] = np.random.randint(1, 50, size)
    df['color'] = np.random.choice(['red','blue','yellow','green'], size)
    df['win'] = np.random.choice(['yes','no'], size)
    dates = pd.date_range('2020-01-01', '2022-12-31')
    df['date'] = np.random.choice(dates, size)
    df['probability'] = np.random.uniform(0, 1, size)
    return df

def set_dtypes(df):
    df['size'] = df['size'].astype('category')
    df['color'] = df['color'].astype('category')
    df['age'] = df['age'].astype('int16')
    df['win'] = df['win'].map({'yes':True, 'no': False})
    df['probability'] = df['probability'].astype('float32')
    return df

In [22]:
df = get_dataset(5_000_000)
df = set_dtypes(df)

In [7]:
print('Reading and writing CSV')

%time df.to_csv('test.csv')
%time df_csv = pd.read_csv('test.csv')

Reading and writing CSV
CPU times: user 14.4 s, sys: 303 ms, total: 14.7 s
Wall time: 14.7 s
CPU times: user 2.39 s, sys: 264 ms, total: 2.66 s
Wall time: 2.66 s

In [6]:
print('Reading and writing Pickle')

%time df.to_pickle("test.pkl")
%time df_pickle = pd.read_pickle("test.pkl")

Reading and writing Pickle
CPU times: user 8.71 ms, sys: 101 ms, total: 110 ms
Wall time: 126 ms
CPU times: user 1.05 ms, sys: 38.9 ms, total: 40 ms
Wall time: 40 ms

In [5]:
print('Reading and writing Feather')

%time df.to_feather("test.feather")
%time df_feather = pd.read_feather("test.feather")

Reading and writing Feather
CPU times: user 261 ms, sys: 63.1 ms, total: 324 ms
Wall time: 203 ms
CPU times: user 140 ms, sys: 102 ms, total: 241 ms
Wall time: 99.6 ms

#### Załaduj ponownie plik csv.
***
Dla osób, które nadpisały obiekt `df`, wracamy do danych samochodowych. Do zmiennej `df` załaduj plik `cars.csv`.

In [23]:
df = pd.read_csv("./cars.csv")
df.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7

#### Posortuj indeksy wierszy, a następnie indeksy kolumn.
***
Podpowiedź: Chodzi o różnicę w wartości parametru `axis`.

In [10]:
df.sort_index(axis=1)

,body_type,color,drivetrain,duration_listed,engine_capacity,engine_fuel,engine_has_gas,engine_type,feature_0,feature_1,...,location_region,manufacturer_name,model_name,number_of_photos,odometer_value,price_usd,state,transmission,up_counter,year_produced
0,universal,silver,all,16,2.5,gasoline,False,gasoline,False,True,...,Минская обл.,Subaru,Outback,9,190000,10900.00,owned,automatic,13,2010
1,universal,blue,all,83,3.0,gasoline,False,gasoline,False,True,...,Минская обл.,Subaru,Outback,12,290000,5000.00,owned,automatic,54,2002
2,suv,red,all,151,2.5,gasoline,False,gasoline,False,True,...,Минская обл.,Subaru,Forester,4,402000,2800.00,owned,automatic,72,2001
3,sedan,blue,all,86,3.0,gasoline,False,gasoline,True,False,...,Минская обл.,Subaru,Impreza,9,10000,9999.00,owned,mechanical,42,1999
4,universal,black,all,7,2.5,gasoline,False,gasoline,False,True,...,Гомельская обл.,Subaru,Legacy,14,280000,2134.11,owned,automatic,7,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,sedan,silver,front,301,3.5,gasoline,False,gasoline,False,True,...,Минская обл.,Chrysler,300,5,290000,2750.00,owned,automatic,85,2000
38527,hatchback,blue,front,317,2.2,diesel,False,diesel,False,True,...,Брестская обл.,Chrysler,PT Cruiser,4,321000,4800.00,owned,mechanical,20,2004
38528,sedan,blue,front,369,3.5,gasoline,False,gasoline,False,True,...,Минская обл.,Chrysler,300,3,777957,4300.00,owned,automatic,63,2000
38529,minivan,black,front,490,2.0,gasoline,False,gasoline,False,True,...,Брестская обл.,Chrysler,PT Cruiser,7,20000,4000.00,owned,mechanical,156,2001
38530,minivan,silver,front,632,2.4,gasoline,False,gasoline,False,False,...,Минская обл.,Chrysler,Voyager,4,297729,3200.00,owned,automatic,73,2000

Czym się różni sortowanie indeksów wierszy i kolumn?

#### Posortuj dane po wartościach w danej kolumnie.
***
Posortuj i wyświetl dane po wartościach w kolumnie `'engine_capacity'`.

In [11]:
df.sort_values('engine_capacity')

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
5932,Mitsubishi,Outlander,automatic,silver,206000,2006,gasoline,False,gasoline,0.2,...,True,True,False,True,True,False,False,True,True,160
30295,Mazda,626,mechanical,red,152369,1993,diesel,False,diesel,0.2,...,False,False,False,False,False,False,False,False,True,2
34685,Mercedes-Benz,190,mechanical,white,340000,1985,gas,True,gasoline,0.2,...,False,False,False,False,False,False,False,False,False,22
11937,Ford,Mondeo,mechanical,green,350000,1995,gasoline,False,gasoline,0.2,...,True,False,False,False,False,False,False,False,False,139
12979,Renault,Scenic,mechanical,red,320,1999,gasoline,False,gasoline,0.2,...,True,False,False,False,False,False,False,False,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26222,Nissan,Leaf,automatic,white,50000,2014,electric,False,electric,NaN,...,True,False,False,False,True,False,True,True,False,18
26582,Nissan,Leaf,automatic,black,84000,2014,electric,False,electric,NaN,...,False,False,False,False,True,True,True,True,True,138
26914,Nissan,Leaf,automatic,black,84500,2013,electric,False,electric,NaN,...,True,False,True,False,True,True,True,True,True,58
27554,BMW,i3,automatic,white,54150,2015,electric,False,electric,NaN,...,True,True,True,False,True,True,True,True,True,18
29590,BMW,i3,automatic,other,67000,2018,electric,False,electric,NaN,...,True,True,True,True,True,True,True,True,True,57

#### Wyświetl, ile różnych wartości przyjmują dane w konkretnej kolumnie?
***
Ile różnych wartości znajduje się w kolumnie `'engine_type'`?

In [14]:
df['engine_type'].unique()

array(['gasoline', 'diesel', 'electric'], dtype=object)

#### Znajdź dane, które znajdują się między konkretnymi indeksami i w konkretnej kolumnie.
***
Wyświetl dane o indeksie między 100, a 1000 i w kolumnie `'engine_capacity'`.

In [24]:
df.loc[100:1000, ['engine_capacity']]

      engine_capacity
100               2.2
101               2.5
102               3.0
103               1.0
104               2.5
...               ...
996               1.8
997               2.9
998               1.6
999               2.0
1000              1.6

[901 rows x 1 columns]

Następnie wyświetl dane o indeksie między 10000, a 20000 i w kolumnach od 0 do 2.

In [25]:
df.iloc[10000:20000, 0:2]

      manufacturer_name model_name
10000              Ford    Transit
10001              Ford     Fiesta
10002              Ford     Fusion
10003              Ford     Mondeo
10004              Ford     Fusion
...                 ...        ...
19995              Audi         A4
19996              Audi         80
19997              Audi         A3
19998              Audi         A4
19999              Audi         80

[10000 rows x 2 columns]

#### Stwórz własny obiekty typu DataFrame i wprowadź do niego różne typy danych.
***
Stwórz i wyświetl obiekt `my_df` zawierający cztery kolumny:
- kolumna "A" powinna zwierać dane typu `float32`,
- kolumna "B" powinna zawierać dane typu `category` o wartościach `'kółko'` albo `'krzyżyk'`,
- kolumna "C" powinna zwierać napis `'Witaj Świecie!'`,
- kolumna "D" powinna zwierać dane typu `Timestamp` z dzisiejszą datą.

In [18]:
my_df = pd.DataFrame({
    "A": np.array([1.2, 2.3], dtype="float32"),
    "B": pd.Categorical(["kółko", "krzyżyk"]),
    "C": ["Witaj Świecie!"]*2,
    "D": [pd.Timestamp.today().normalize()]*2})

my_df.head()

     A        B               C          D
0  1.2    kółko  Witaj Świecie! 2026-03-02
1  2.3  krzyżyk  Witaj Świecie! 2026-03-02